def main():
    raise Exception
    print('123')

try:
    main()
except Exception:
    print('-1')